# Generated by Django 3.0 on 2023-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apelidopate', models.CharField(default='', max_length=100, verbose_name='Apellido_paterno')),
                ('apelidomater', models.CharField(default='', max_length=100, verbose_name='Apellidom')),
            ],
        ),
    ]
