# Generated by Django 3.0 on 2023-07-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.CharField(default='', max_length=100, verbose_name='edad'),
        ),
    ]
