# Generated by Django 3.0 on 2023-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', max_length=100, verbose_name='celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(default='', max_length=100, verbose_name='genero'),
        ),
    ]
