# Generated by Django 3.0 on 2023-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20230713_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dinero', models.CharField(default='', max_length=100, verbose_name='cantidad')),
                ('tipocomprador', models.CharField(default='', max_length=1, verbose_name='tipocomprador')),
                ('metodopago', models.CharField(default='', max_length=1, verbose_name='metodopago')),
            ],
        ),
    ]
